# Example Grafana custom values for production
adminPassword: "<secure-password>"
persistence:
  enabled: true
  size: 10Gi
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 1Gi
